name: Third Workflow
on: [push]

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: Display some text
        run: echo "Some text"
      - name: Command in multiline
        run: |
          pwd
          ls -a